### ISSUE TITLE
Planning errors with 2 spades from cult bonus

### ISSUE THREAD

**Issue by EGrunzke** [jsnell/terra-mystica#10]
I'm in a game and have 2 spades coming from a cult reward.  The main game lets me transform properly, but the planner gives a "Must spend spades received from cult before next move." error even with the same moves.  Like so:

![multiple-transforms-planning-bug](https://cloud.githubusercontent.com/assets/12192108/10988197/91af89aa-83f7-11e5-9a4e-9ff0191ad6e1.png)

Here's the game to see it in the wild.
http://terra.snellman.net/faction/tryhardmode003/cultists/

**Comment by jsnell** [comment]
Thanks, should work correctly now.
