### ISSUE TITLE
"Problem" in a two play game when the starting play is dropped.

### ISSUE THREAD

**Issue by ASealion** [jsnell/terra-mystica#11]
I was in a two player game "1221" when the admin/creater of the game was dropped out due to his 12h time limit.
After that I had no change to end the game only the using "resign", that gave me a bad mark 
(at least in my opinion) because I haven't quit the game or was dropped out. I simply had no other change.

**Comment by jsnell** [comment]
So it didn't give you an option to take any moves? Or there was an option
to take a move, but you didn't want to play out the game (which I do
realize is busywork, but should just be 2 dwellings and 6 passes)?

Anyway, your rating will not have been affected by this game, and the
"dropped" counter is not used for anything, it's just cosmetic.

On 30 November 2015 at 12:40, ASealion <notifications@github.com> wrote:

> I was in a two player game "1221" when the admin/creater of the game was
> dropped out due to his 12h time limit.
> After that I had no change to end the game only the using "resign", that
> gave me a bad mark
> (at least in my opinion) because I haven't quit the game or was dropped
> out. I simply had no other change.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsnell/terra-mystica/issues/11>.
>



-- 
Juho Snellman

**Comment by ASealion** [comment]
There was the possibility to take an action. But when I selected one, I could not save my move but have to take an other one and so on and so on.
I think after 4 or 5 action in the list all coins and worker were gone and still I couldn't save. (The only actions left was the power actions but i haven't tried and further and simply used the resign command.

**Comment by jsnell** [comment]
Saving is only possible if (after the moves have been executed) it's someone else's turn or the game is over. So you would just have needed to take some pass actions until the game ended.
