### ISSUE TITLE
Add map information to Terra Mystica server events json data?

### ISSUE THREAD

**Issue by ceridwen** [jsnell/terra-mystica#14]
At the moment, I don't see a way in the http://terra.snellman.net/data/events/ json files to tell which map a game is played on.  This would be a useful bit of information that (I hope) wouldn't be too hard or space-intensive to add, and it would help me improve the data from my statistics scripts :).  (If it's already there somewhere and I haven't found it, please point me to the right place.)

**Comment by jsnell** [comment]
It's there (field base_map)
