### ISSUE TITLE
Add type of expansion scoring (edge, SA-SH distance, and so on) to events JSON data

### ISSUE THREAD

**Issue by ceridwen** [jsnell/terra-mystica#15]
I looked under `option-fire-and-ice-final-scoring`, but as far as I could tell that always has the same values under it.

**Comment by jsnell** [comment]
Hi,

It's not in the json at the moment.

**Comment by jsnell** [comment]
They're now available, under events.global.scoring-{building-on-edge,connected-distance,connected-clusters,connected-sa-sh-distance}
