### ISSUE TITLE
Player/faction order in the json?

### ISSUE THREAD

**Issue by ceridwen** [jsnell/terra-mystica#16]
Is there a way to determine this?  The "faction" object isn't ordered, as you'd expect.  I looked in the round 0 events data and there doesn't seem to be any useful information from the "order:x" events.

**Comment by jsnell** [comment]
The order:* events should be it. For example order:1 will be set to 1 for the faction that started that round, 0 for the other factions, order:2 set to 1 for the faction that was second in the round, etc.
