### ISSUE TITLE
Stalling with the 'done' command

### ISSUE THREAD

**Issue by tresh** [jsnell/terra-mystica#18]
Scenario:
- I want to get the BON of the other player in a 1on1 situation but I have no other possible actions or do not want to use any other actions
- I use the 'done' command to pass to the other player
- It is now the other players turn who also uses 'done' to pass the turn back

The current scenario is currently unfolding in one of my games (see [0]). Maybe I missed a part in the rules but it seems that the 'done' command can be abused to skip your own turn in order to get the BON of a player who'd pass after you (or for other shenanigans). Is this intended? Can I tell the player that this is a bug and he should just pass?

[0]: https://terra.snellman.net/faction/univie09/

**Comment by jsnell** [comment]
Yes, it's a bug. Using "done" should only be possible if you've already taken an action. (The command is intended to be used just for cases where you want to e.g. do a transform and a build on separate turns).

Thanks a lot for the report.

**Comment by jsnell** [comment]
Hi,

One more quick question on this. It looks to me that the "done" button should already have been disabled in the UI under these circumstances. Were you guys manually typing in "done"?

**Comment by tresh** [comment]
Sorry for the late answer. Yes, me and my friend did it by manually inserting the 'done' command in the 'console'. The 'done' button was disabled.
