### ISSUE TITLE
Change from IPv4 to IPv6 messing with SPF

### ISSUE THREAD

**Issue by tresh** [jsnell/terra-mystica#20]
I guess that the recent change at terra.snellman.net which enabled IPv6 incidentally downgraded GMails SPF rating from PASS to NEUTRAL. I don't know much about SPF but I think it is probably caused by a (missing filter)[0] or the like. The problem might cause e-mails sent by terra.snellman.net to be marked as spam (as it happened to me but I can only tell for GMail).

While this does not really concern the terra-mystica code I hope it is alright that I'm still reporting it here.

Best regards,
David

[0]: http://www.openspf.org/SPF_Record_Syntax#ip6

**Comment by jsnell** [comment]
I've actually never had an SPF record set up, I suspect Google has just over time learned a domain/IP association, and is reporting the status of that using the same mechanism as actual SPF lookups.

Anyway, I've added an SPF record now, hopefully it'll clear things up.

**Comment by tresh** [comment]
Looks fixed to me, thanks a lot.
