### ISSUE TITLE
Feature request: "+income" planning command

### ISSUE THREAD

**Issue by sparr** [jsnell/terra-mystica#29]
I want to plan across multiple turns without needing to deal with cult income or other game-mandatory decisions that are troublesome for me to predict. I find that I have to plan one turn, then look at my income, then +c +p +pw, then plan the next turn. But if I go back and change something about the first turn then I need to re-check its results and change the income lines. I would love to be able to just stick "+income" or something similar in there to have it bump my resources by whatever my current income level is.

**Comment by sparr** [comment]
I find that I need this feature less now that I've built up a collection of reference game turns so I know what actions the game is expecting at each juncture. I'd love to see better documentation of this, or more guidance in the web interface, but I see that this particular request isn't quite right.

**Comment by jsnell** [comment]
I don't really understand the use case in the first place. What's wrong with just planning a "pass"?

**Comment by sparr** [comment]
There's no feedback on the required steps after passing, such as using spades from scoring.
