### ISSUE TITLE
Setup Local Environment

### ISSUE THREAD

**Issue by chadsaun** [jsnell/terra-mystica#3]
What kind of settings do I need in Apache to get this running on my local machine?

**Comment by bcgraham** [comment]
I've set up `update-active-time.pl`, `abort-idle-games.pl`, and `drop-idle-players.pl` on cron to run every 10 minutes, and `genratings.pl` and `genstats.pl` to run daily. Is this reasonable/how you've got it set up? Anything else to keep in mind?

**Comment by jsnell** [comment]
Ah, yes. There is indeed stuff that needs to be run from cron. I've added a config/crontab.example

What you have are reasonable numbers, they get the only thing that's absolutely required right (update-active-time needs a 10 minute interval or it'll misbehave). There's no explicit script to clear old entries from the to_validate table, I do that once a day:

25 4 * * * psql terra-mystica -c "delete from to_validate where created_at < now() - '2 weeks'::interval;"

You've got everything else running smoothly?

**Comment by bcgraham** [comment]
Yes. What you wrote above was a big help, thanks. I put some notes/remarks in the wiki.

**Comment by codybuell** [comment]
Piggy backing on this issue since it's still open.  Working to setup on Ubuntu 16.04 server and having trouble debugging, just not familiar enough with Perl.  On the registration page I get "An unknown error occured" when submitting.

error.log:

```
Devel::StackTrace::new('Devel::StackTrace') called at Util/Watchdog.pm line 12
  Util::Watchdog::__ANON__('ALRM') called at /usr/local/share/perl/5.22.1/Crypt/Random/Seed.pm line 174
  eval {...} at /usr/local/share/perl/5.22.1/Crypt/Random/Seed.pm line 174
  Crypt::Random::Seed::__read_file('/dev/random', 32) called at /usr/local/share/perl/5.22.1/Crypt/Random/Seed.pm line 162
  Crypt::Random::Seed::__ANON__(32) called at /usr/local/share/perl/5.22.1/Crypt/Random/Seed.pm line 140
  Crypt::Random::Seed::random_values('Crypt::Random::Seed=HASH(0x50c1290)', 8) called at /usr/local/share/perl/5.22.1/Bytes/Random/Secure.pm line 205
  Bytes::Random::Secure::_generate_seed('Bytes::Random::Secure=HASH(0x50bb8d8)', 'Weak', 0, 'NonBlocking', 0) called at /usr/local/share/perl/5.22.1/Bytes/Random/Secure.pm line 171
  Bytes::Random::Secure::_instantiate_rng('Bytes::Random::Secure=HASH(0x50bb8d8)') called at /usr/local/share/perl/5.22.1/Bytes/Random/Secure.pm line 227
  Bytes::Random::Secure::bytes('Bytes::Random::Secure=HASH(0x50bb8d8)', 16) called at /usr/local/share/perl/5.22.1/Bytes/Random/Secure.pm line 382
  Bytes::Random::Secure::random_bytes(16) called at Server/Register.pm line 70
  Server::Register::request_registration('Server::Register=HASH(0x4f5daa8)', 'Server::Request=HASH(0x50b0030)', 'DBI::db=HASH(0x50bb578)') called at Server/Register.pm line 30
  Server::Register::handle('Server::Register=HASH(0x4f5daa8)', 'Server::Request=HASH(0x50b0030)', '') called at Server/Router.pm line 153
  Server::Router::__ANON__ at Util/Watchdog.pm line 31
  eval {...} at Util/Watchdog.pm line 29
  Util::Watchdog::with_watchdog(15, 'CODE(0x50af4d8)') called at Server/Router.pm line 155
Request timed out
FastCGI: manager (pid 4670): server (pid 4671) exited with status 256
FastCGI: manager (pid 4670): server (pid 4743) started
FastCGI: server (pid 4743): initialized
```

terra-error.log

```
[Thu Jan 05 15:43:28.980455 2017] [fastcgi:error] [pid 4667] [client 65.127.220.140:30377] FastCGI: incomplete headers (0 bytes) received from server "/var/www/vhosts/terra-mystica/www-devel/lib/app.fcgi", referer: http://xxxxxxxxxxxxx.com/register/request/
```

**Comment by jsnell** [comment]
Hm. So that's suggesting that on your system reading from /dev/random is currently blocking. Which could happen in theory if the system really has no entropy at all, but we're talking of just reading 16 bytes from there.

But there's really no point in using /dev/random anyway, not sure why Bytes::Random::Secure is defaulting to it. I've pushed a commit to switch it to use /dev/urandom instead, does that fix the issue for you?

**Comment by codybuell** [comment]
That seems to have done the trick!

**Comment by JamesWolfpacker** [comment]
Hi, @chadsaun  @bcgraham  @codybuell  @5outh  @jsnell 

I'm looking for someone who is already familiar with the Terra Mystica code from Juho to make some alterations and additions for a separate and private playtesting server for future Terra Mystica expansions. Is anyone interested in doing it? Juho mentioned where some of the additions might need to happen. Thank you!

**Comment by 5outh** [comment]
Hm, I'm not familiar with it (or Perl); my contributions so far have only been copy changes. Hope you find what you're looking for, though!

**Comment by chadsaun** [comment]
Sorry, I'm not a Perl guy either and haven't done much with this. Good luck!

**Comment by codybuell** [comment]
Don’t know how much availability I’d have.  What in particular are you looking to do?

**Comment by JamesWolfpacker** [comment]
I'll send you an e-mail at your site.
