### ISSUE TITLE
Instructions for running local server

### ISSUE THREAD

**Issue by amalloy** [jsnell/terra-mystica#42]
I'm interested in investigating a possible bug, and wanted to reproduce it locally so that I can (a) confirm that it exists, and (b) try fixing it if so. But I don't see anything in the README about how to run it myself. It looks like deploy.pl might do it, but I'm not sure how to use that script, or what dependencies it has on how my system is already set up.

**Comment by jsnell** [comment]
https://github.com/jsnell/terra-mystica/wiki/Local-environment-setup has instructions that explains most of the process, though there might be some gaps.
