### ISSUE TITLE
Undocumented options

### ISSUE THREAD

**Issue by salty-horse** [jsnell/terra-mystica#6]
Hey,

The following default options are not documented in `usage.org`:
* strict-leech
* strict-darkling-sh
* strict-chaosmagician-sh
* errata-cultist-power

**Comment by jsnell** [comment]
Thanks. But only options that users might want to change are documented.

There are about a dozen of options, including the above four, that are essentially implementation details. They deal with cases where bugfixes, rules clarifications or outright rules changes would cause some existing games to become invalid. But there will never be any reason for anyone except the site admin to care about those options.
