### ISSUE TITLE
logfile swallows faction after color pick in setup

### ISSUE THREAD

**Issue by DocCool** [jsnell/terra-mystica#8]
After the last player X has picked a color during setup (expansion factions), the first initial building by the first player Y is wrongly attributed to X in the logfile. Game flow is not affected.

Example from game [stans135] (http://terra.snellman.net/game/stans135):
> alchemists		20 VP		15 C		3 W		0 P		5/7/0 PW		1/1/0/0 		setup
> dragonlords		20 VP		15 C		3 W		0 P		4/4/0 PW		2/0/0/0 		setup
> dragonlords		20 VP		15 C		3 W		0 P		4/4/0 PW		2/0/0/0 		pick-color brown. build E3
> fakirs		20 VP		15 C		3 W		0 P		7/5/0 PW		1/0/0/1 		build D5

The "build E3" is actually an action by the first player (in this game: Auren).

**Comment by jsnell** [comment]
Fixed a while ago
