### ISSUE TITLE
Planning mode lets you dig as a cult reward with BON4

### ISSUE THREAD

**Issue by EGrunzke** [jsnell/terra-mystica#9]
In a [recent game](http://terra.snellman.net/game/4pLeague_S9_D6L15_G6/max-row=224), I did some planning:

    Send P to Air.
    Send P to Air.
    Pass BON4.
    Transform I9 to Red.

The round bonus was 4 Air -> Spade, and I needed the +1Ship from BON4 to reach I9.  This worked in planning, but when it was executed in the real game, it informed me that I9 was out of reach.  After reading the FAQ, I know this is the correct behavior, but it would be good if the planning pane respected the same rules as the "real" one.

**Comment by jsnell** [comment]
Indeed. It's a known issue that's very tricky to fix due to the way the planner works. But I've added a section on this to the "Known issues" part of the manual.

**Comment by jsnell** [comment]
This should no longer be possible, as of a couple of weeks ago.

**Comment by EGrunzke** [comment]
Oh wow!  Thanks for the fix.  I was happy with just the update to the manual :smiley:
